//All verses from Douay-Rheims Challoner Revision 1752
export const verses: Record<string, string> = {
	1: '\n ☩ 1 Corinthians 10:13 ☩\n\n Let no temptation take hold on you, but such as is human.\n And God is faithful, who will not suffer you to be tempted above that which you are able:\n but will make also with temptation issue, that you may be able to bear it.\n',
	2: '\n ☩ Matthew 26:41 ☩\n\n Watch ye, and pray that ye enter not into temptation.\n The spirit indeed is willing, but the flesh weak.\n',
	3: '\n ☩ Isaiah 53:5 ☩\n\n But he was wounded for our iniquities: he was bruised for our sins.\n The chastisement of our peace was upon him, and by his bruises we are healed.\n',
	4: '\n ☩ John 13:7 ☩\n\n Jesus answered, and said to him: What I do thou knowest not now;\n but thou shalt know hereafter.\n',
	5: '\n ☩ Galatians 5:22-23 ☩\n\n But the fruit of the Spirit is, charity, joy, peace, patience, benignity,\n goodness, longanimity, mildness, faith, modesty, continency, chastity.\n Against such there is no law.\n',
	6: '\n ☩ Psalms 34:4 ☩\n\n Let them be confounded and ashamed that seek after my soul.\n Let them be turned back and be confounded that devise against me.\n',
	7: '\n ☩ 1 Corinthians 13:4-8 ☩\n\n Charity is patient, is kind: Charity envieth not,\n dealeth not perversely; Is not puffed up; Is not ambitious,\n seeketh not her own, is not provoked to anger, thinketh no evil;\n Rejoiceth not in iniquity, but rejoiceth with the truth;\n Beareth all things, believeth all things, hopeth all things, endureth all things.\n Charity never falleth away: whether prophecies shall be made void,\n or tongues shall cease, or knowledge shall be destroyed.\n',
	8: '\n ☩ Isaiah 60:22 ☩\n\n The least shall become a thousand, and a little one a most strong nation:\n I, the Lord, will suddenly do this thing in its time.\n',
	9: '\n ☩ Ezekiel 36:26 ☩\n\n And I will give you a new heart, and put a new spirit within you:\n and I will take away the stony heart out of your flesh, and will give you a heart of flesh.\n',
	10: '\n ☩ Galatians 6:7-8 ☩\n\n Be not deceived, God is not mocked. For what things a man shall sow, those also shall he reap.\n For he that soweth in his flesh, of the flesh also shall reap corruption.\n But he that soweth in the spirit, of the spirit shall reap life everlasting.\n',
	11: '\n ☩ Job 31:1 ☩\n\n I made a covenant with my eyes, that I would not so much as think upon a virgin.\n',
	12: '\n ☩ Jeremiah 29:11 ☩\n\n For I know the thoughts that I think towards you, saith the Lord,\n thoughts of peace and not of affliction, to give you an end and patience.\n',
	13: '\n ☩ Isaiah 40:30-31 ☩\n\n Youths shall faint and labour: and young men shall fall by infirmity.\n But they that hope in the Lord shall renew their strength: they shall take wings as eagles;\n they shall run and not be weary; they shall walk and not faint.\n',
	14: '\n ☩ Phillipians 4:13 ☩\n\n I can do all these things in him who strengtheneth me.\n',
	15: '\n ☩ Proverbs 24:16 ☩\n\n For a just man shall fall seven times and shall rise again:\n but the wicked shall fall down into evil.\n',
	16: '\n ☩ 1 Timothy 2:5-6 ☩\n For there is one God, and one mediator of God and men, the man Christ Jesus:\n Who gave himself a redemption for all, a testimony in due times.\n',
	17: '\n ☩ 1 Peter 5:10 ☩\n But the God of all grace, who hath called us into his eternal glory in Christ Jesus,\n after you have suffered a little, will himself perfect you,\n and confirm you, and establish you.\n',
	18: '\n ☩ Luke 6:37 ☩\n Judge not, and you shall not be judged. Condemn not, and you shall not be condemned.\n Forgive, and you shall be forgiven.\n',
};
